DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS links CASCADE;
DROP TABLE IF EXISTS account_creations;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS logs;
