[package]
name = "db"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sqlx = { version = "0.7.1", features = ["postgres", "runtime-tokio-rustls"] }
